version: '3'

services:
  frontend:
    build:
      context: ./Frontend  # Path to your Vue.js project
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./Backend  # Path to your Node.js project
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - backend