version: '3'

services:
  frontend:
    build:
      context: ./Frontend  # Path to your Vue.js project
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./Backend  # Path to your Node.js project
    ports:
      - "3000:3000"
    depends_on:
      - frontend