name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Stop existing Docker containers
      run: docker-compose down
    - name: Fetch latest changes
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Run Git Pull
      run: git pull

    - name: Run Docker Compose
      run: docker-compose up -d --build && docker ps
