name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Stop existing Docker containers
      run: sudo docker-compose down || true
    
    - name: Fetch latest changes
      uses: actions/checkout@v2
    
    - name: Create common Folder
      run: |
        mkdir ~/actions-runner/_work/vpedia/vpedia/Backend/common/ || true


    - name: Move creds files
      run: |
        cp ~/config.json ~/actions-runner/_work/vpedia/vpedia/Backend/config/
        cp ~/constents.js ~/actions-runner/_work/vpedia/vpedia/Backend/common/
        cp ~/.env ~/actions-runner/_work/vpedia/vpedia/Frontend/
    - name: Run Docker Compose
      run: sudo docker-compose up -d --build && docker ps
